version: 2.1

orbs:
  # Using 1.0 of the Orbs means it will use the latest 1.0.x version from https://github.com/wordpress-mobile/circleci-orbs
  ios: wordpress-mobile/ios@1.0
  git: wordpress-mobile/git@1.0

jobs:
  Build Tests:
    executor:
      name: ios/default
      xcode-version: "11.2.1"
    steps:
      - git/shallow-checkout
      - ios/install-dependencies:
            bundle-install: true
            pod-install: true
      - ios/xcodebuild:
          command: build-for-testing
          arguments: -workspace 'Newspack.xcworkspace' -scheme 'Newspack' -configuration 'Debug' -sdk iphonesimulator -derivedDataPath DerivedData
      - persist_to_workspace:
          root: ./
          paths:
            - DerivedData/Build/Products
  Unit Tests:
    executor:
      name: ios/default
      xcode-version: "11.2.1"
    steps:
      - ios/boot-simulator:
          xcode-version: "11.2.1"
          device: iPhone 11
      - attach_workspace:
          at: ./
      - ios/wait-for-simulator
      - ios/xcodebuild:
          command: test-without-building
          arguments: -xctestrun DerivedData/Build/Products/Newspack_iphonesimulator13.2-x86_64.xctestrun -destination "platform=iOS Simulator,id=$SIMULATOR_UDID" -resultBundlePath test-without-building.xcresult
      - ios/save-xcodebuild-artifacts
  Installable Build:
    executor:
      name: ios/default
      xcode-version: "11.2.1"
    steps:
      - git/shallow-checkout
      - ios/install-dependencies:
            bundle-install: true
            pod-install: true
      - run:
          name: Copy Secrets
          command: bundle exec fastlane run configure_apply
      - run:
          name: Build
          command: "bundle exec fastlane build_and_upload_installable_build build_number:$CIRCLE_BUILD_NUM"
      - run:
          name: Prepare Artifacts
          command: |
            mkdir -p Artifacts
            mv "fastlane/comment.json" "Artifacts/comment.json"
      - store_artifacts:
          path: Artifacts
          destination: Artifacts

workflows:
  newspack_ios:
    jobs:
      - Build Tests
      - Unit Tests:
          requires: [ "Build Tests" ]
  Installable Build:
    jobs:
      - Hold:
          type: approval
          filters:
            branches:
              ignore: /pull\/[0-9]+/
      - Installable Build:
          requires: [Hold]  
          filters:
            branches:
              ignore: /pull\/[0-9]+/

  